# Generated by Django 5.0.4 on 2024-04-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_nam_chapter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='done',
            field=models.IntegerField(default=0, verbose_name='Количество сделанных задач'),
        ),
        migrations.AddField(
            model_name='board',
            name='not_done',
            field=models.IntegerField(default=0, verbose_name='Количество не сделанных задач'),
        ),
        migrations.AlterField(
            model_name='task',
            name='check_list',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Чек лист'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Низкий'), (1, 'Средний'), (2, 'Высокий')], default=1, verbose_name='Приоритет'),
        ),
    ]
