# Generated by Django 5.0.4 on 2024-04-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_file_task_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, related_name='tasks', to='tasks.file'),
        ),
    ]
